plugins:
  - "@typescript-eslint"
  - import
extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended
  - plugin:astro/recommended
rules:
  "import/order":
    - warn
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      pathGroups:
        - pattern: "{react,react-dom/**,react-router-dom}"
          group: builtin
          position: after
        - pattern: "{astro,astro/**,@astrojs/**,astro:**}"
          group: builtin
          position: after
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
      newlines-between: always
  "@typescript-eslint/consistent-type-imports":
    - warn
    - prefer: type-imports
  "@typescript-eslint/no-var-requires":
    - off
overrides:
  - files:
      - "*.astro"
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions:
        - ".astro"
    rules: {}
