name: Alpha Deployment

on:
  push:
    branches:
      - dev

jobs:
  alpha-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - name: Setup pnpm with corepack
        run: |
          corepack enable pnpm
          corepack prepare pnpm@latest --activate
          SHELL="$(which bash)" pnpm setup
          source ~/.bashrc
          echo "$PNPM_HOME" >> $GITHUB_PATH
      - name: Get pnpm store path
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm store & build artifact cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-astro-
      - name: Install node dependencies
        run: pnpm i --frozen-lockfile
      - name: Install Wrangler CLI
        run: pnpm add -g wrangler
      - name: Check types and code styles
        run: pnpm run lint && pnpm run format-check
      - name: Build project artifacts
        run: pnpm run build
      - name: Deploy project artifacts to Cloudflare Pages
        run: wrangler pages deploy ./dist --project-name=mythfinder --branch alpha
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
