name: Production Deployment

on:
  push:
    branches:
      - main

env:
  PNPM_HOME: /home/runner/.local/share/pnpm

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - name: Configure pnpm path
        run: echo "${{ env.PNPM_HOME }}" >> $GITHUB_PATH
      - name: Setup pnpm with corepack
        run: |
          corepack enable pnpm
          corepack prepare pnpm@latest --activate
          SHELL="$(which bash)" pnpm setup --force
      - name: Get pnpm store path
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm store & build artifact cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-astro-
      - name: Install node dependencies
        run: pnpm i --frozen-lockfile
      - name: Install Chrome binary
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Install Wrangler CLI
        run: pnpm add -g wrangler
      - name: Build project artifacts
        run: pnpm run build
      - name: Deploy project artifacts to Cloudflare Pages
        run: wrangler pages deploy ./dist --project-name=mythfinder --branch main
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
