name: pr-test

on: [pull_request]

env:
  node-version: 14
  pnpm-version: latest
  workdir: ./haxibami.net

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: |
              ~/.pnpm-store
              ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        with: 
          version: ${{ env.pnpm-version }}
          run_install: |
            - recursive: true
              args: [--strict-peer-dependencies=false]
      - name: Test build
        run: pnpm run build
